def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contracts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('client', sa.String(), nullable=True),
    sa.Column('pep', sa.String(length=18), nullable=True),
    sa.Column('folio', sa.String(), nullable=True),
    sa.Column('service_type', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('sdm', sa.String(), nullable=True),
    sa.Column('sales_rep', sa.String(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pep')
    )
    op.create_index(op.f('ix_contracts_client'), 'contracts', ['client'], unique=False)
    
    op.create_table('contract_cis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contract_id', sa.String(), nullable=True),
    sa.Column('ci_name', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contract_cis_id'), 'contract_cis', ['id'], unique=False)
    # ### end Alembic commands ###

def downgrade():
    op.drop_table('contract_cis')
    op.drop_table('contracts')
