"""add_contract_desc_project

Revision ID: 8345b104bc05
Revises: f425bee5723a
Create Date: 2026-01-31 22:47:03.416730

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8345b104bc05'
down_revision: Union[str, Sequence[str], None] = 'f425bee5723a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contracts', sa.Column('description', sa.String(), nullable=True))
    op.add_column('contracts', sa.Column('project_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contracts', 'project_name')
    op.drop_column('contracts', 'description')
    # ### end Alembic commands ###
